### ISSUE TITLE
Bad version in `Cargo.lock` for 0.2.0

### ISSUE THREAD

**Issue by herbygillot** [uzimaru0000/tv#17]
Just a note that the `Cargo.lock` in the **0.2.0** branch of `tv` has `tv`'s version set to **0.1.2**:

https://github.com/uzimaru0000/tv/blob/768f9afe7732d0a93e219c9bac5e08d1e9ecdd86/Cargo.lock#L392

Something to watch out for in future releases.

**Comment by uzimaru0000** [comment]
Thank you for reporting!!
I will run `cargo c` before the release.

**Comment by herbygillot** [comment]
Thank you
