### ISSUE TITLE
Do you mean "plain" instead of "plane"?

### ISSUE THREAD

**Issue by tanquar** [uzimaru0000/tv#38]
In the styling options, do you actually mean "plain" instead of "plane"?

cf
https://ejje.weblio.jp/content/plain
"装飾のない"

cf
https://ejje.weblio.jp/content/plane
"平らな"

**Comment by uzimaru0000** [comment]
"plain" is correct!
If it's not too much trouble, may I ask you to create a revised PR for me?

**Comment by tanquar** [comment]
Sure, I opened #39

**Comment by uzimaru0000** [comment]
Resolved #39 
Thank you!
