### ISSUE TITLE
[Brew] No such file or directory - completions/zsh/_tv

### ISSUE THREAD

**Issue by MikeKnowles** [uzimaru0000/tv#41]
Seems there's either an issue with a [tv.rb](https://github.com/uzimaru0000/homebrew-tap/blob/099980a407a6a9aa0e8e07a90909aef2f2e80ac5/Formula/tv.rb) or the way the release zip is created

Basically the directory in the zip is currently flat and looks like

```
tv-x86_64-apple-darwin
├── LICENSE
├── README.md
├── _tv
├── tv
├── tv.bash
├── tv.d
└── tv.fish
```

**Comment by uzimaru0000** [comment]
Thank you for reporting!
Currently, I have made some [temporary changes](https://github.com/uzimaru0000/homebrew-tap/blob/master/Formula/tv.rb#L10).  I know [the fix](https://github.com/uzimaru0000/tv/blob/master/.github/workflows/release.yml#L60), so I plan to fix it by the next release.

**Comment by uzimaru0000** [comment]
fixed it
