### ISSUE TITLE
Features you want to add

### ISSUE THREAD

**Issue by uzimaru0000** [uzimaru0000/tv#7]
I am looking for features that you would like to add.
It will be provided as a minimum command, so it will be rejected in some cases.

**Comment by gatosyocora** [comment]
These are just ideas. No problem to reject.
- sort
- execute query
- simple display to pass to other commands
  - e.g. ) without frames (data rows only)
- output for markdown table

**Comment by uzimaru0000** [comment]
Thank you!!!

> * sort
> * simple display to pass to other commands
>   * e.g. ) without frames (data rows only)
> * output for markdown table

Nice idea!!
This idea could be implemented as an option!

> * execute query

I think you should use [jq](https://stedolan.github.io/jq/)

I will make issues with this idea 👍

**Comment by uzimaru0000** [comment]
This topic move to https://github.com/uzimaru0000/tv/discussions/26
